using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NtefyWeb.Business
{
    public static class CountryCodes
    {
        public static List<KeyValuePair<string, string>> CreateCountryList()
        {
            var list = new List<KeyValuePair<string, string>>();
            list.Add(new KeyValuePair<string, string>("AD", "Andorra"));
            list.Add(new KeyValuePair<string, string>("AE", "United Arab Emirates"));
            list.Add(new KeyValuePair<string, string>("AF", "Afghanistan"));
            list.Add(new KeyValuePair<string, string>("AG", "Antigua and Barbuda"));
            list.Add(new KeyValuePair<string, string>("AI", "Anguilla"));
            list.Add(new KeyValuePair<string, string>("AL", "Albania"));
            list.Add(new KeyValuePair<string, string>("AM", "Armenia"));
            list.Add(new KeyValuePair<string, string>("AO", "Angola"));
            list.Add(new KeyValuePair<string, string>("AQ", "Antarctica"));
            list.Add(new KeyValuePair<string, string>("AR", "Argentina"));
            list.Add(new KeyValuePair<string, string>("AS", "American Samoa"));
            list.Add(new KeyValuePair<string, string>("AT", "Austria"));
            list.Add(new KeyValuePair<string, string>("AU", "Australia"));
            list.Add(new KeyValuePair<string, string>("AW", "Aruba"));
            list.Add(new KeyValuePair<string, string>("AX", "Åland Islands"));
            list.Add(new KeyValuePair<string, string>("AZ", "Azerbaijan"));
            list.Add(new KeyValuePair<string, string>("BA", "Bosnia and Herzegovina"));
            list.Add(new KeyValuePair<string, string>("BB", "Barbados"));
            list.Add(new KeyValuePair<string, string>("BD", "Bangladesh"));
            list.Add(new KeyValuePair<string, string>("BE", "Belgium"));
            list.Add(new KeyValuePair<string, string>("BF", "Burkina Faso"));
            list.Add(new KeyValuePair<string, string>("BG", "Bulgaria"));
            list.Add(new KeyValuePair<string, string>("BH", "Bahrain"));
            list.Add(new KeyValuePair<string, string>("BI", "Burundi"));
            list.Add(new KeyValuePair<string, string>("BJ", "Benin"));
            list.Add(new KeyValuePair<string, string>("BL", "Saint Barthélemy"));
            list.Add(new KeyValuePair<string, string>("BM", "Bermuda"));
            list.Add(new KeyValuePair<string, string>("BN", "Brunei Darussalam"));
            list.Add(new KeyValuePair<string, string>("BO", "Bolivia, Plurinational State of"));
            list.Add(new KeyValuePair<string, string>("BQ", "Bonaire, Sint Eustatius and Saba"));
            list.Add(new KeyValuePair<string, string>("BR", "Brazil"));
            list.Add(new KeyValuePair<string, string>("BS", "Bahamas"));
            list.Add(new KeyValuePair<string, string>("BT", "Bhutan"));
            list.Add(new KeyValuePair<string, string>("BV", "Bouvet Island"));
            list.Add(new KeyValuePair<string, string>("BW", "Botswana"));
            list.Add(new KeyValuePair<string, string>("BY", "Belarus"));
            list.Add(new KeyValuePair<string, string>("BZ", "Belize"));
            list.Add(new KeyValuePair<string, string>("CA", "Canada"));
            list.Add(new KeyValuePair<string, string>("CC", "Cocos (Keeling) Islands"));
            list.Add(new KeyValuePair<string, string>("CD", "Congo, the Democratic Republic of the"));
            list.Add(new KeyValuePair<string, string>("CF", "Central African Republic"));
            list.Add(new KeyValuePair<string, string>("CG", "Congo"));
            list.Add(new KeyValuePair<string, string>("CH", "Switzerland"));
            list.Add(new KeyValuePair<string, string>("CI", "Côte d'Ivoire"));
            list.Add(new KeyValuePair<string, string>("CK", "Cook Islands"));
            list.Add(new KeyValuePair<string, string>("CL", "Chile"));
            list.Add(new KeyValuePair<string, string>("CM", "Cameroon"));
            list.Add(new KeyValuePair<string, string>("CN", "China"));
            list.Add(new KeyValuePair<string, string>("CO", "Colombia"));
            list.Add(new KeyValuePair<string, string>("CR", "CR"));
            list.Add(new KeyValuePair<string, string>("CU", "Cuba"));
            list.Add(new KeyValuePair<string, string>("CV", "Cabo Verde"));
            list.Add(new KeyValuePair<string, string>("CW", "Curaçao"));
            list.Add(new KeyValuePair<string, string>("CX", "Christmas Island"));
            list.Add(new KeyValuePair<string, string>("CY", "Cyprus"));
            list.Add(new KeyValuePair<string, string>("CZ", "Czech Republic"));
            list.Add(new KeyValuePair<string, string>("DE", "Germany"));
            list.Add(new KeyValuePair<string, string>("DJ", "Djibouti"));
            list.Add(new KeyValuePair<string, string>("DK", "Denmark"));
            list.Add(new KeyValuePair<string, string>("DM", "Dominica"));
            list.Add(new KeyValuePair<string, string>("DO", "Dominican Republic"));
            list.Add(new KeyValuePair<string, string>("DZ", "Algeria"));
            list.Add(new KeyValuePair<string, string>("EE", "Estonia"));
            list.Add(new KeyValuePair<string, string>("EG", "Egypt"));
            list.Add(new KeyValuePair<string, string>("EH", "Western Sahara"));
            list.Add(new KeyValuePair<string, string>("ER", "Eritrea"));
            list.Add(new KeyValuePair<string, string>("ES", "Spain"));
            list.Add(new KeyValuePair<string, string>("ET", "Ethiopia"));
            list.Add(new KeyValuePair<string, string>("FI", "Finland"));
            list.Add(new KeyValuePair<string, string>("FJ", "Fiji"));
            list.Add(new KeyValuePair<string, string>("FK", "Falkland Islands (Malvinas)"));
            list.Add(new KeyValuePair<string, string>("FM", "Micronesia, Federated States of"));
            list.Add(new KeyValuePair<string, string>("FO", "Faroe Islands"));
            list.Add(new KeyValuePair<string, string>("FR", "France"));
            list.Add(new KeyValuePair<string, string>("GA", "Gabon"));
            list.Add(new KeyValuePair<string, string>("GB", "United Kingdom"));
            list.Add(new KeyValuePair<string, string>("GD", "Grenada"));
            list.Add(new KeyValuePair<string, string>("GE", "Georgia"));
            list.Add(new KeyValuePair<string, string>("GF", "French Guiana"));
            list.Add(new KeyValuePair<string, string>("GG", "Guernsey"));
            list.Add(new KeyValuePair<string, string>("GH", "Ghana"));
            list.Add(new KeyValuePair<string, string>("GI", "Gibraltar"));
            list.Add(new KeyValuePair<string, string>("GL", "Greenland"));
            list.Add(new KeyValuePair<string, string>("GM", "Gambia"));
            list.Add(new KeyValuePair<string, string>("GN", "Guinea"));
            list.Add(new KeyValuePair<string, string>("GP", "Guadeloupe"));
            list.Add(new KeyValuePair<string, string>("GQ", "Equatorial Guinea"));
            list.Add(new KeyValuePair<string, string>("GR", "Greece"));
            list.Add(new KeyValuePair<string, string>("GS", "South Georgia and the South Sandwich Islands"));
            list.Add(new KeyValuePair<string, string>("GT", "Guatemala"));
            list.Add(new KeyValuePair<string, string>("GU", "Guam"));
            list.Add(new KeyValuePair<string, string>("GQ", "Guinea-Bissau"));
            list.Add(new KeyValuePair<string, string>("GY", "Guyana"));
            list.Add(new KeyValuePair<string, string>("HK", "Hong Kong"));
            list.Add(new KeyValuePair<string, string>("HM", "Heard Island and McDonald Islands"));
            list.Add(new KeyValuePair<string, string>("HN", "Honduras"));
            list.Add(new KeyValuePair<string, string>("HR", "Croatia"));
            list.Add(new KeyValuePair<string, string>("HT", "Haiti"));
            list.Add(new KeyValuePair<string, string>("HU", "Hungary"));
            list.Add(new KeyValuePair<string, string>("ID", "Indonesia"));
            list.Add(new KeyValuePair<string, string>("IE", "Ireland"));
            list.Add(new KeyValuePair<string, string>("IL", "Israel"));
            list.Add(new KeyValuePair<string, string>("IM", "Isle of Man"));
            list.Add(new KeyValuePair<string, string>("IN", "India"));
            list.Add(new KeyValuePair<string, string>("IO", "British Indian Ocean Territory"));
            list.Add(new KeyValuePair<string, string>("IQ", "Iraq"));
            list.Add(new KeyValuePair<string, string>("IR", "Iran, Islamic Republic of"));
            list.Add(new KeyValuePair<string, string>("IS", "Iceland"));
            list.Add(new KeyValuePair<string, string>("IT", "Italy"));
            list.Add(new KeyValuePair<string, string>("JE", "Jersey"));
            list.Add(new KeyValuePair<string, string>("JM", "Jamaica"));
            list.Add(new KeyValuePair<string, string>("JO", "Jordan"));
            list.Add(new KeyValuePair<string, string>("JP", "Japan"));
            list.Add(new KeyValuePair<string, string>("KE", "Kenya"));
            list.Add(new KeyValuePair<string, string>("KG", "Kyrgyzstan"));
            list.Add(new KeyValuePair<string, string>("KH", "Cambodia"));
            list.Add(new KeyValuePair<string, string>("KI", "Kiribati"));
            list.Add(new KeyValuePair<string, string>("KM", "Comoros"));
            list.Add(new KeyValuePair<string, string>("KN", "Saint Kitts and Nevis"));
            list.Add(new KeyValuePair<string, string>("KP", "Korea, Democratic People's Republic of"));
            list.Add(new KeyValuePair<string, string>("KR", "Korea, Republic of"));
            list.Add(new KeyValuePair<string, string>("KW", "Kuwait"));
            list.Add(new KeyValuePair<string, string>("KY", "Cayman Islands"));
            list.Add(new KeyValuePair<string, string>("KZ", "Kazakhstan"));
            list.Add(new KeyValuePair<string, string>("LA", "Lao People's Democratic Republic"));
            list.Add(new KeyValuePair<string, string>("LB", "Lebanon"));
            list.Add(new KeyValuePair<string, string>("LC", "Saint Lucia"));
            list.Add(new KeyValuePair<string, string>("LI", "Liechtenstein"));
            list.Add(new KeyValuePair<string, string>("LK", "Sri Lanka"));
            list.Add(new KeyValuePair<string, string>("LR", "Liberia"));
            list.Add(new KeyValuePair<string, string>("LS", "Lesotho"));
            list.Add(new KeyValuePair<string, string>("LT", "Lithuania"));
            list.Add(new KeyValuePair<string, string>("LU", "Luxembourg"));
            list.Add(new KeyValuePair<string, string>("LV", "Latvia"));
            list.Add(new KeyValuePair<string, string>("LY", "Libya"));
            list.Add(new KeyValuePair<string, string>("MA", "Morocco"));
            list.Add(new KeyValuePair<string, string>("MC", "Monaco"));
            list.Add(new KeyValuePair<string, string>("MD", "Moldova, Republic of"));
            list.Add(new KeyValuePair<string, string>("ME", "Montenegro"));
            list.Add(new KeyValuePair<string, string>("MF", "Saint Martin (French part)"));
            list.Add(new KeyValuePair<string, string>("MG", "Madagascar"));
            list.Add(new KeyValuePair<string, string>("MH", "Marshall Islands"));
            list.Add(new KeyValuePair<string, string>("MK", "Macedonia, the former Yugoslav Republic of"));
            list.Add(new KeyValuePair<string, string>("ML", "Mali"));
            list.Add(new KeyValuePair<string, string>("MM", "Myanmar"));
            list.Add(new KeyValuePair<string, string>("MN", "Mongolia"));
            list.Add(new KeyValuePair<string, string>("MO", "Macao"));
            list.Add(new KeyValuePair<string, string>("MP", "Northern Mariana Islands"));
            list.Add(new KeyValuePair<string, string>("MQ", "Martinique"));
            list.Add(new KeyValuePair<string, string>("MR", "Mauritania"));
            list.Add(new KeyValuePair<string, string>("MS", "Montserrat"));
            list.Add(new KeyValuePair<string, string>("MT", "Malta"));
            list.Add(new KeyValuePair<string, string>("MU", "Mauritius"));
            list.Add(new KeyValuePair<string, string>("MV", "Maldives"));
            list.Add(new KeyValuePair<string, string>("MW", "Malawi"));
            list.Add(new KeyValuePair<string, string>("MX", "Mexico"));
            list.Add(new KeyValuePair<string, string>("MY", "Malaysia"));
            list.Add(new KeyValuePair<string, string>("MZ", "Mozambique"));
            list.Add(new KeyValuePair<string, string>("NA", "Namibia"));
            list.Add(new KeyValuePair<string, string>("NC", "New Caledonia"));
            list.Add(new KeyValuePair<string, string>("NE", "Niger"));
            list.Add(new KeyValuePair<string, string>("NF", "Norfolk Island"));
            list.Add(new KeyValuePair<string, string>("NG", "Nigeria"));
            list.Add(new KeyValuePair<string, string>("NI", "Nicaragua"));
            list.Add(new KeyValuePair<string, string>("NL", "Netherlands"));
            list.Add(new KeyValuePair<string, string>("NO", "Norway"));
            list.Add(new KeyValuePair<string, string>("NP", "Nepal"));
            list.Add(new KeyValuePair<string, string>("NR", "Nauru"));
            list.Add(new KeyValuePair<string, string>("NU", "Niue"));
            list.Add(new KeyValuePair<string, string>("NZ", "New Zealand"));
            list.Add(new KeyValuePair<string, string>("OM", "Oman"));
            list.Add(new KeyValuePair<string, string>("PA", "Panama"));
            list.Add(new KeyValuePair<string, string>("PE", "Peru"));
            list.Add(new KeyValuePair<string, string>("PF", "French Polynesia"));
            list.Add(new KeyValuePair<string, string>("PG", "Papua New Guinea"));
            list.Add(new KeyValuePair<string, string>("PH", "Philippines"));
            list.Add(new KeyValuePair<string, string>("PK", "Pakistan"));
            list.Add(new KeyValuePair<string, string>("PL", "Poland"));
            list.Add(new KeyValuePair<string, string>("PM", "Saint Pierre and Miquelon"));
            list.Add(new KeyValuePair<string, string>("PN", "Pitcairn"));
            list.Add(new KeyValuePair<string, string>("PR", "Puerto Rico"));
            list.Add(new KeyValuePair<string, string>("PS", "Palestine, State of"));
            list.Add(new KeyValuePair<string, string>("PT", "Portugal"));
            list.Add(new KeyValuePair<string, string>("PW", "Palau"));
            list.Add(new KeyValuePair<string, string>("PY", "Paraguay"));
            list.Add(new KeyValuePair<string, string>("QA", "Qatar"));
            list.Add(new KeyValuePair<string, string>("RE", "Réunion"));
            list.Add(new KeyValuePair<string, string>("RO", "Romania"));
            list.Add(new KeyValuePair<string, string>("RS", "Serbia"));
            list.Add(new KeyValuePair<string, string>("RU", "Russian Federation"));
            list.Add(new KeyValuePair<string, string>("RW", "Rwanda"));
            list.Add(new KeyValuePair<string, string>("SA", "Saudi Arabia"));
            list.Add(new KeyValuePair<string, string>("SB", "Solomon Islands"));
            list.Add(new KeyValuePair<string, string>("SC", "Seychelles"));
            list.Add(new KeyValuePair<string, string>("SD", "Sudan"));
            list.Add(new KeyValuePair<string, string>("SE", "Sweden"));
            list.Add(new KeyValuePair<string, string>("SG", "Singapore"));
            list.Add(new KeyValuePair<string, string>("SH", "Saint Helena, Ascension and Tristan da Cunha"));
            list.Add(new KeyValuePair<string, string>("SI", "Slovenia"));
            list.Add(new KeyValuePair<string, string>("SJ", "Svalbard and Jan Mayen"));
            list.Add(new KeyValuePair<string, string>("SK", "Slovakia"));
            list.Add(new KeyValuePair<string, string>("SL", "Sierra Leone"));
            list.Add(new KeyValuePair<string, string>("SM", "San Marino"));
            list.Add(new KeyValuePair<string, string>("SN", "Senegal"));
            list.Add(new KeyValuePair<string, string>("SO", "Somalia"));
            list.Add(new KeyValuePair<string, string>("SR", "Suriname"));
            list.Add(new KeyValuePair<string, string>("SS", "South Sudan"));
            list.Add(new KeyValuePair<string, string>("ST", "Sao Tome and Principe"));
            list.Add(new KeyValuePair<string, string>("SV", "El Salvador"));
            list.Add(new KeyValuePair<string, string>("SX", "Sint Maarten (Dutch part)"));
            list.Add(new KeyValuePair<string, string>("SY", "Syrian Arab Republic"));
            list.Add(new KeyValuePair<string, string>("SZ", "Swaziland"));
            list.Add(new KeyValuePair<string, string>("TC", "Turks and Caicos Islands"));
            list.Add(new KeyValuePair<string, string>("TD", "Chad"));
            list.Add(new KeyValuePair<string, string>("TF", "French Southern Territories"));
            list.Add(new KeyValuePair<string, string>("TG", "Togo"));
            list.Add(new KeyValuePair<string, string>("TH", "Thailand"));
            list.Add(new KeyValuePair<string, string>("TJ", "Tajikistan"));
            list.Add(new KeyValuePair<string, string>("TK", "Tokelau"));
            list.Add(new KeyValuePair<string, string>("TL", "Timor-Leste"));
            list.Add(new KeyValuePair<string, string>("TM", "Turkmenistan"));
            list.Add(new KeyValuePair<string, string>("TN", "Tunisia"));
            list.Add(new KeyValuePair<string, string>("TO", "Tonga"));
            list.Add(new KeyValuePair<string, string>("TR", "Turkey"));
            list.Add(new KeyValuePair<string, string>("TT", "Trinidad and Tobago"));
            list.Add(new KeyValuePair<string, string>("TV", "Tuvalu"));
            list.Add(new KeyValuePair<string, string>("TW", "Taiwan, Province of China"));
            list.Add(new KeyValuePair<string, string>("TZ", "Tanzania, United Republic of"));
            list.Add(new KeyValuePair<string, string>("UA", "Ukraine"));
            list.Add(new KeyValuePair<string, string>("UG", "Uganda"));
            list.Add(new KeyValuePair<string, string>("UM", "United States Minor Outlying Islands"));
            list.Add(new KeyValuePair<string, string>("US", "United States of America"));
            list.Add(new KeyValuePair<string, string>("UY", "Uruguay"));
            list.Add(new KeyValuePair<string, string>("UZ", "Uzbekistan"));
            list.Add(new KeyValuePair<string, string>("VA", "Holy See"));
            list.Add(new KeyValuePair<string, string>("VC", "Saint Vincent and the Grenadines"));
            list.Add(new KeyValuePair<string, string>("VE", "Venezuela, Bolivarian Republic of"));
            list.Add(new KeyValuePair<string, string>("VG", "Virgin Islands, British"));
            list.Add(new KeyValuePair<string, string>("VI", "Virgin Islands, U.S."));
            list.Add(new KeyValuePair<string, string>("VN", "Viet Nam"));
            list.Add(new KeyValuePair<string, string>("VU", "Vanuatu"));
            list.Add(new KeyValuePair<string, string>("WF", "Wallis and Futuna"));
            list.Add(new KeyValuePair<string, string>("WS", "Samoa"));
            list.Add(new KeyValuePair<string, string>("YE", "Yemen"));
            list.Add(new KeyValuePair<string, string>("YT", "Mayotte"));
            list.Add(new KeyValuePair<string, string>("ZA", "South Africa"));
            list.Add(new KeyValuePair<string, string>("ZM", "Zambia"));
            list.Add(new KeyValuePair<string, string>("ZW", "Zimbabwe"));

            var sortedList = list.OrderBy(x => x.Value).ToList();

            return sortedList;

        }
    }
}